background #121210
foreground #FFFFFF
cursor #FFFFFF
cursor_text_color #121210
selection_foreground #FFFFFF
selection_background #242424
active_border_color #a30202
inactive_border_color #181818
url_color #a30202
active_tab_foreground #121210
active_tab_background #a30202
inactive_tab_foreground #AAAAAA
inactive_tab_background #181818

color0 #181818
color1 #FF3B30
color2 #34C759
color3 #f9e2af
color4 #a30202
color5 #cba6f7
color6 #89dceb
color7 #AAAAAA
color8 #242424
color9 #FF3B30
color10 #34C759
color11 #f9e2af
color12 #a30202
color13 #cba6f7
color14 #89dceb
color15 #FFFFFF
